
import { Phoneme } from './types';

export const PULMONIC_CONSONANTS: Phoneme[] = [
  { symbol: 'p', category: 'Plosive', description: 'Voiceless bilabial plosive', example: 'pin' },
  { symbol: 'b', category: 'Plosive', description: 'Voiced bilabial plosive', example: 'bin' },
  { symbol: 't', category: 'Plosive', description: 'Voiceless alveolar plosive', example: 'tin' },
  { symbol: 'd', category: 'Plosive', description: 'Voiced alveolar plosive', example: 'din' },
  { symbol: 'ʈ', category: 'Plosive', description: 'Voiceless retroflex plosive', example: 'Hindi' },
  { symbol: 'ɖ', category: 'Plosive', description: 'Voiced retroflex plosive', example: 'Hindi' },
  { symbol: 'c', category: 'Plosive', description: 'Voiceless palatal plosive', example: 'Hungarian' },
  { symbol: 'ɟ', category: 'Plosive', description: 'Voiced palatal plosive', example: 'Hungarian' },
  { symbol: 'k', category: 'Plosive', description: 'Voiceless velar plosive', example: 'kin' },
  { symbol: 'g', category: 'Plosive', description: 'Voiced velar plosive', example: 'give' },
  { symbol: 'q', category: 'Plosive', description: 'Voiceless uvular plosive', example: 'Arabic' },
  { symbol: 'ɢ', category: 'Plosive', description: 'Voiced uvular plosive', example: 'Persian' },
  { symbol: 'ʔ', category: 'Plosive', description: 'Glottal stop', example: 'uh-oh' },
  { symbol: 'm', category: 'Nasal', description: 'Bilabial nasal', example: 'man' },
  { symbol: 'ɱ', category: 'Nasal', description: 'Labiodental nasal', example: 'emphasis' },
  { symbol: 'n', category: 'Nasal', description: 'Alveolar nasal', example: 'no' },
  { symbol: 'ɳ', category: 'Nasal', description: 'Retroflex nasal', example: 'Hindi' },
  { symbol: 'ɲ', category: 'Nasal', description: 'Palatal nasal', example: 'canyon' },
  { symbol: 'ŋ', category: 'Nasal', description: 'Velar nasal', example: 'sing' },
  { symbol: 'ɴ', category: 'Nasal', description: 'Uvular nasal', example: 'Japanese' },
  { symbol: 'ʙ', category: 'Trill', description: 'Bilabial trill', example: 'brrr' },
  { symbol: 'r', category: 'Trill', description: 'Alveolar trill', example: 'perro' },
  { symbol: 'ʀ', category: 'Trill', description: 'Uvular trill', example: 'French r' },
  { symbol: 'ⱱ', category: 'Tap/Flap', description: 'Labiodental flap', example: 'African languages' },
  { symbol: 'ɾ', category: 'Tap/Flap', description: 'Alveolar tap', example: 'better' },
  { symbol: 'ɽ', category: 'Tap/Flap', description: 'Retroflex flap', example: 'Hindi' },
  { symbol: 'ɸ', category: 'Fricative', description: 'Voiceless bilabial fricative', example: 'Japanese f' },
  { symbol: 'β', category: 'Fricative', description: 'Voiced bilabial fricative', example: 'Spanish b' },
  { symbol: 'f', category: 'Fricative', description: 'Voiceless labiodental fricative', example: 'fan' },
  { symbol: 'v', category: 'Fricative', description: 'Voiced labiodental fricative', example: 'van' },
  { symbol: 'θ', category: 'Fricative', description: 'Voiceless dental fricative', example: 'thin' },
  { symbol: 'ð', category: 'Fricative', description: 'Voiced dental fricative', example: 'this' },
  { symbol: 's', category: 'Fricative', description: 'Voiceless alveolar fricative', example: 'sun' },
  { symbol: 'z', category: 'Fricative', description: 'Voiced alveolar fricative', example: 'zoo' },
  { symbol: 'ʃ', category: 'Fricative', description: 'Voiceless postalveolar fricative', example: 'she' },
  { symbol: 'ʒ', category: 'Fricative', description: 'Voiced postalveolar fricative', example: 'measure' },
  { symbol: 'ʂ', category: 'Fricative', description: 'Voiceless retroflex fricative', example: 'Mandarin sh' },
  { symbol: 'ʐ', category: 'Fricative', description: 'Voiced retroflex fricative', example: 'Russian zhe' },
  { symbol: 'ç', category: 'Fricative', description: 'Voiceless palatal fricative', example: 'German ich' },
  { symbol: 'ʝ', category: 'Fricative', description: 'Voiced palatal fricative', example: 'Spanish y' },
  { symbol: 'x', category: 'Fricative', description: 'Voiceless velar fricative', example: 'Loch' },
  { symbol: 'ɣ', category: 'Fricative', description: 'Voiced velar fricative', example: 'Greek g' },
  { symbol: 'χ', category: 'Fricative', description: 'Voiceless uvular fricative', example: 'Hebrew' },
  { symbol: 'ʁ', category: 'Fricative', description: 'Voiced uvular fricative', example: 'French r' },
  { symbol: 'ħ', category: 'Fricative', description: 'Voiceless pharyngeal fricative', example: 'Arabic' },
  { symbol: 'ʕ', category: 'Fricative', description: 'Voiced pharyngeal fricative', example: 'Arabic' },
  { symbol: 'h', category: 'Fricative', description: 'Voiceless glottal fricative', example: 'hat' },
  { symbol: 'ɦ', category: 'Fricative', description: 'Voiced glottal fricative', example: 'ahead' },
  { symbol: 'ɬ', category: 'Lateral Fricative', description: 'Voiceless alveolar lateral fricative', example: 'Welsh ll' },
  { symbol: 'ɮ', category: 'Lateral Fricative', description: 'Voiced alveolar lateral fricative', example: 'Zulu' },
  { symbol: 'ʋ', category: 'Approximant', description: 'Labiodental approximant', example: 'Dutch w' },
  { symbol: 'ɹ', category: 'Approximant', description: 'Alveolar approximant', example: 'run' },
  { symbol: 'ɻ', category: 'Approximant', description: 'Retroflex approximant', example: 'American r' },
  { symbol: 'j', category: 'Approximant', description: 'Palatal approximant', example: 'yes' },
  { symbol: 'ɰ', category: 'Approximant', description: 'Velar approximant', example: 'Spanish g' },
  { symbol: 'l', category: 'Lateral Approximant', description: 'Alveolar lateral approximant', example: 'let' },
  { symbol: 'ɭ', category: 'Lateral Approximant', description: 'Retroflex lateral approximant', example: 'Tamil' },
  { symbol: 'ʎ', category: 'Lateral Approximant', description: 'Palatal lateral approximant', example: 'Italian gl' },
  { symbol: 'ʟ', category: 'Lateral Approximant', description: 'Velar lateral approximant', example: 'Melpa' },
  { symbol: 'w', category: 'Co-articulated', description: 'Voiced labio-velar approximant', example: 'wet' },
  { symbol: 'ʍ', category: 'Co-articulated', description: 'Voiceless labio-velar fricative', example: 'which' },
  { symbol: 'ɥ', category: 'Co-articulated', description: 'Voiced labio-palatal approximant', example: 'French huit' },
  { symbol: 'ʜ', category: 'Co-articulated', description: 'Voiceless epiglottal fricative', example: 'Agul' },
  { symbol: 'ʢ', category: 'Co-articulated', description: 'Voiced epiglottal fricative', example: 'Arabic' },
  { symbol: 'ʡ', category: 'Co-articulated', description: 'Epiglottal stop', example: 'Amis' },
  { symbol: 'ɕ', category: 'Fricative', description: 'Voiceless alveolo-palatal fricative', example: 'Mandarin' },
  { symbol: 'ʑ', category: 'Fricative', description: 'Voiced alveolo-palatal fricative', example: 'Polish' },
  { symbol: 'ɧ', category: 'Fricative', description: 'Simultaneous voiceless postalveolar and velar fricative', example: 'Swedish' },
];

export const NON_PULMONIC: Phoneme[] = [
  { symbol: 'ʘ', category: 'Click', description: 'Bilabial click', example: 'Kissing sound' },
  { symbol: 'ǀ', category: 'Click', description: 'Dental click', example: 'tsk-tsk' },
  { symbol: 'ǃ', category: 'Click', description: 'Alveolar click', example: 'Clucking sound' },
  { symbol: 'ǂ', category: 'Click', description: 'Palatoalveolar click', example: 'African languages' },
  { symbol: 'ǁ', category: 'Click', description: 'Alveolar lateral click', example: 'Jockey sound' },
  { symbol: 'ɓ', category: 'Implosive', description: 'Voiced bilabial implosive', example: 'Swahili' },
  { symbol: 'ɗ', category: 'Implosive', description: 'Voiced alveolar implosive', example: 'Hausa' },
  { symbol: 'ʄ', category: 'Implosive', description: 'Voiced palatal implosive', example: 'Sindhi' },
  { symbol: 'ɠ', category: 'Implosive', description: 'Voiced velar implosive', example: 'Ewe' },
  { symbol: 'ʛ', category: 'Implosive', description: 'Voiced uvular implosive', example: 'Mam' },
  { symbol: 'ʼ', category: 'Ejective', description: 'Ejective marker', example: 'p\'' },
];

export const VOWELS: Phoneme[] = [
  { symbol: 'i', category: 'Front', description: 'Close front unrounded', example: 'see' },
  { symbol: 'y', category: 'Front', description: 'Close front rounded', example: 'French u' },
  { symbol: 'ɨ', category: 'Central', description: 'Close central unrounded', example: 'Russian y' },
  { symbol: 'ʉ', category: 'Central', description: 'Close central rounded', example: 'Swedish u' },
  { symbol: 'ɯ', category: 'Back', description: 'Close back unrounded', example: 'Turkish i' },
  { symbol: 'u', category: 'Back', description: 'Close back rounded', example: 'too' },
  { symbol: 'ɪ', category: 'Front', description: 'Near-close front unrounded', example: 'bit' },
  { symbol: 'ʏ', category: 'Front', description: 'Near-close front rounded', example: 'German hütte' },
  { symbol: 'ʊ', category: 'Back', description: 'Near-close back rounded', example: 'put' },
  { symbol: 'e', category: 'Front', description: 'Close-mid front unrounded', example: 'Spanish e' },
  { symbol: 'ø', category: 'Front', description: 'Close-mid front rounded', example: 'French peu' },
  { symbol: 'ɘ', category: 'Central', description: 'Close-mid central unrounded', example: 'ExtIPA' },
  { symbol: 'ɵ', category: 'Central', description: 'Close-mid central rounded', example: 'ExtIPA' },
  { symbol: 'ɤ', category: 'Back', description: 'Close-mid back unrounded', example: 'Mandarin e' },
  { symbol: 'o', category: 'Back', description: 'Close-mid back rounded', example: 'Spanish o' },
  { symbol: 'ə', category: 'Central', description: 'Schwa (mid central)', example: 'about' },
  { symbol: 'ɛ', category: 'Front', description: 'Open-mid front unrounded', example: 'bed' },
  { symbol: 'œ', category: 'Front', description: 'Open-mid front rounded', example: 'French peur' },
  { symbol: 'ɜ', category: 'Central', description: 'Open-mid central unrounded', example: 'bird' },
  { symbol: 'ɞ', category: 'Central', description: 'Open-mid central rounded', example: 'ExtIPA' },
  { symbol: 'ʌ', category: 'Back', description: 'Open-mid back unrounded', example: 'but' },
  { symbol: 'ɔ', category: 'Back', description: 'Open-mid back rounded', example: 'thought' },
  { symbol: 'æ', category: 'Front', description: 'Near-open front unrounded', example: 'bat' },
  { symbol: 'ɐ', category: 'Central', description: 'Near-open central', example: 'German er' },
  { symbol: 'a', category: 'Open', description: 'Open front unrounded', example: 'Spanish a' },
  { symbol: 'ɶ', category: 'Open', description: 'Open front rounded', example: 'ExtIPA' },
  { symbol: 'ɑ', category: 'Back', description: 'Open back unrounded', example: 'father' },
  { symbol: 'ɒ', category: 'Back', description: 'Open back rounded', example: 'lot' },
];

export const EXT_IPA: Phoneme[] = [
  { symbol: 'ᶑ', category: 'ExtIPA', description: 'Voiced alveolar implosive (extIPA)', example: 'ExtIPA' },
  { symbol: 'ʦ', category: 'Affricate', description: 'Voiceless alveolar affricate', example: 'cats' },
  { symbol: 'ʣ', category: 'Affricate', description: 'Voiced alveolar affricate', example: 'kids' },
  { symbol: 'ʧ', category: 'Affricate', description: 'Voiceless postalveolar affricate', example: 'church' },
  { symbol: 'ʤ', category: 'Affricate', description: 'Voiced postalveolar affricate', example: 'judge' },
  { symbol: 'ʨ', category: 'Affricate', description: 'Voiceless alveolo-palatal affricate', example: 'Mandarin' },
  { symbol: 'ʥ', category: 'Affricate', description: 'Voiced alveolo-palatal affricate', example: 'Japanese' },
  { symbol: 'ꭦ', category: 'ExtIPA', description: 'Voiceless lateral-release alveolar plosive', example: 'ExtIPA' },
  { symbol: 'ꭧ', category: 'ExtIPA', description: 'Voiced lateral-release alveolar plosive', example: 'ExtIPA' },
  { symbol: '𝼅', category: 'ExtIPA', description: 'Voiced lateral-release palatal plosive', example: 'ExtIPA' },
  { symbol: '𝼄', category: 'ExtIPA', description: 'Voiceless lateral-release palatal plosive', example: 'ExtIPA' },
  { symbol: 'ꞎ', category: 'ExtIPA', description: 'Voiceless retroflex lateral fricative', example: 'ExtIPA' },
  { symbol: '𝼈', category: 'ExtIPA', description: 'Retroflex lateral flap', example: 'ExtIPA' },
  { symbol: '𝼆', category: 'ExtIPA', description: 'Voiced palatal lateral fricative', example: 'ExtIPA' },
  { symbol: '𝼊', category: 'ExtIPA', description: 'Sublaminal lower alveolar click', example: 'ExtIPA' },
  { symbol: 'ɺ', category: 'Tap/Flap', description: 'Alveolar lateral flap', example: 'Japanese' },
  { symbol: 'ɫ', category: 'Approximant', description: 'Velarized alveolar lateral approximant', example: 'feel' },
  { symbol: '∅', category: 'Empty', description: 'Empty set / Zero', example: 'Morphology' },
];

export const DIACRITICS: Phoneme[] = [
  { symbol: 'ʰ', category: 'Secondary', description: 'Aspirated', example: 'pʰ' },
  { symbol: 'ʷ', category: 'Secondary', description: 'Labialized', example: 'kʷ' },
  { symbol: 'ʲ', category: 'Secondary', description: 'Palatalized', example: 'tʲ' },
  { symbol: 'ˠ', category: 'Secondary', description: 'Velarized', example: 'tˠ' },
  { symbol: 'ˤ', category: 'Secondary', description: 'Pharyngealized', example: 'tˤ' },
  { symbol: 'ⁿ', category: 'Secondary', description: 'Nasal release', example: 'dⁿ' },
  { symbol: 'ˡ', category: 'Secondary', description: 'Lateral release', example: 'dˡ' },
  { symbol: 'ː', category: 'Suprasegmental', description: 'Long', example: 'aː' },
  { symbol: 'ˑ', category: 'Suprasegmental', description: 'Half-long', example: 'aˑ' },
  { symbol: '̆', category: 'Suprasegmental', description: 'Extra-short', example: 'ă' },
  { symbol: '̃', category: 'Diacritic', description: 'Nasalized', example: 'ã' },
  { symbol: '̥', category: 'Diacritic', description: 'Voiceless', example: 'n̥' },
  { symbol: '̬', category: 'Diacritic', description: 'Voiced', example: 's̬' },
  { symbol: '̤', category: 'Diacritic', description: 'Breathy voiced', example: 'a̤' },
  { symbol: '̰', category: 'Diacritic', description: 'Creaky voiced', example: 'a̰' },
  { symbol: '̪', category: 'Diacritic', description: 'Dental', example: 't̪' },
  { symbol: '̈', category: 'Diacritic', description: 'Centralized', example: 'ë' },
  { symbol: '̽', category: 'Diacritic', description: 'Mid-centralized', example: 'e̽' },
  { symbol: '̩', category: 'Diacritic', description: 'Syllabic', example: 'n̩' },
  { symbol: '̯', category: 'Diacritic', description: 'Non-syllabic', example: 'e̯' },
  { symbol: '˞', category: 'Diacritic', description: 'Rhoticity', example: 'a˞' },
  { symbol: '̘', category: 'Diacritic', description: 'Advanced tongue root', example: 'e̘' },
  { symbol: '̙', category: 'Diacritic', description: 'Retracted tongue root', example: 'e̙' },
  { symbol: '̝', category: 'Diacritic', description: 'Raised', example: 'e̝' },
  { symbol: '̞', category: 'Diacritic', description: 'Lowered', example: 'e̞' },
  { symbol: '̟', category: 'Diacritic', description: 'Advanced', example: 'u̟' },
  { symbol: '̠', category: 'Diacritic', description: 'Retracted', example: 'i̠' },
  { symbol: '̺', category: 'Diacritic', description: 'Apical', example: 't̺' },
  { symbol: '̻', category: 'Diacritic', description: 'Laminal', example: 't̻' },
  { symbol: '̼', category: 'Diacritic', description: 'Linguolabial', example: 't̼' },
  { symbol: '̹', category: 'Diacritic', description: 'More rounded', example: 'ɔ̹' },
  { symbol: '̜', category: 'Diacritic', description: 'Less rounded', example: 'ɔ̜' },
  { symbol: '̚', category: 'Diacritic', description: 'No audible release', example: 'd̚' },
  { symbol: '͡', category: 'Connector', description: 'Tie bar (above)', example: 't͡s' },
];

export const TONES_STRESS: Phoneme[] = [
  { symbol: 'ˈ', category: 'Stress', description: 'Primary stress', example: 'ˈapple' },
  { symbol: 'ˌ', category: 'Stress', description: 'Secondary stress', example: 'ˌapple' },
  { symbol: '˥', category: 'Tone', description: 'Extra high tone', example: 'Tone 5' },
  { symbol: '˦', category: 'Tone', description: 'High tone', example: 'Tone 4' },
  { symbol: '˧', category: 'Tone', description: 'Mid tone', example: 'Tone 3' },
  { symbol: '˨', category: 'Tone', description: 'Low tone', example: 'Tone 2' },
  { symbol: '˩', category: 'Tone', description: 'Extra low tone', example: 'Tone 1' },
];

export const PRESETS = [
  { name: 'Mediterranean', description: 'Rich in vowels, simple syllable structure. Sounds like Italian or Greek.', phonemes: ['p', 'b', 't', 'd', 'k', 'g', 'm', 'n', 'f', 'v', 's', 'z', 'l', 'r', 'i', 'u', 'e', 'o', 'a'] },
  { name: 'Nordic', description: 'Harsh consonants, complex clusters. Sounds like Old Norse.', phonemes: ['p', 't', 'k', 'f', 's', 'h', 'm', 'n', 'ŋ', 'l', 'j', 'w', 'i', 'u', 'y', 'e', 'o', 'a', 'ø', 'ʰ'] },
  { name: 'East Asian', description: 'Limited consonants, potential for nasal endings and tones.', phonemes: ['p', 't', 'k', 'm', 'n', 's', 'h', 'j', 'w', 'i', 'u', 'e', 'o', 'a', '˥', '˧', '˩'] },
  { name: 'Clicks & Ejectives', description: 'Complex sounds inspired by Southern African languages.', phonemes: ['p', 't', 'k', 'ʘ', 'ǀ', 'ǃ', 'ǂ', 'ǁ', 'ɓ', 'ɗ', 'ʼ', 'm', 'n', 'a', 'i', 'u'] },
];
